### ISSUE TITLE
Vyhledávání faktur - pagination

### ISSUE THREAD

**Issue by terezaklobouckova** [redbitcz/vyfakturuj-apiary#2]
V dokumentaci píšete, že tento endpoint má podporovat pagination se stránkami o 25 záznamech přičemž pro stránkování se má používat rows_offset. Zdá se, že toto nefunguje. Všechen obsah je mi pokaždé navrácen v jednom callu. Když implementuji row_offset, dostanu se do nekonečné smyčky.

Můžete se na to prosím podívat? Děkuji

**Comment by Dosty85** [comment]
Dokumentaci jsme upravili. Do budoucna se opravdu počítá s 25 záznamy na 1 request. Aktuálně je tato hodnota nastavena na 1000.
O změně budeme včas informovat.

Doporučujeme použít již nyní:

```
$opt = array(
    'rows_limit' => 25,
    'rows_offset' => 0 // page2 = 25, page3 = 50, page4 = 75
);

$inv = $vyfakturuj_api->getInvoices($opt);
```
