### ISSUE TITLE
Pole "vat_rate" - nepropisující se hodnota

### ISSUE THREAD

**Issue by devintegromat** [redbitcz/vyfakturuj-apiary#3]
Při pokusu o vytvoření faktury o různých položkách se nepropíše "vat_rate". Respektive ať co posíláme za číslo, tak se vždy vrátí jako nula.

Jedná se o bug nebo to má něco společného s nastavením DPH v GUI aplikace Vyfakturuj.cz?

**Comment by Vyfakturuj-cz** [comment]
Není firma nastavená jako neplátce DPH? V takovém případě bude hodnota vždy 0. Stejně tak Identifikovaná osoba. Když nám pošlete `API ID` z Nastavení -> API, tak se na konkrétní request podíváme a pošleme více informací. Ideální by bylo toto komunikovat přes naši podporu. Stačí napsat z aplikace přes `Zeptejste se nás`. Tak se request dostane nejrychleji k nám vývojářům a zároveň budeme mít i další potřebné infomace ;-)

**Comment by Dosty85** [comment]
Pro neaktivitu zavírám.
