### ISSUE TITLE
Formátování dat v URL webhooku

### ISSUE THREAD

**Issue by devintegromat** [redbitcz/vyfakturuj-apiary#4]
Po nastavení webhooku se posílá tato struktura:
/fhehcmvtkgn4xdpgl13gcfsclr9wn332?mail=tomas%40frydek.cz&cislo_objednavky=420200110&firstname=TomÃ¡Å¡&lastname=FrÃ½dek&total=1999.00

Jak již můžete vidět, české znaky nejsou URL encodované a tudíž neodpovídají. Např. pro jméno Tomáš se vygeneruje řezězec TomÃ¡Å¡. Můžete prosím do adresy webhooku přidat URL encodování?

**Comment by jakubboucek** [comment]
Díky za report.

Potvrzuju, že reportu jsem porozuměl, předávám to na vývoj, ozvu s dalšími informacemi.

PS: Prosím, napříště, pokud nebude problém přímo s dokumentací, ale bude spočívat ve špatném chování backendu, nepožívejte issues u zdrojových kódů nápovědy API, ale kontaktujte nás přímo na [**Zákaznické podpoře Vyfakturuj.cz**](https://www.vyfakturuj.cz/kontakt/). Díky moc.

**Comment by jakubboucek** [comment]
@devintegromat Potvrzuji nalezenou chybu, některé parametry jsou skutečně do URL předávány chybně. Na opravě pracujeme.

**Comment by jakubboucek** [comment]
@devintegromat Právě jsme vydali novou verzi aplikace, která má kódování znaků v URL opravené.
